#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/threaded/scheduler.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
int lf_reactor_c_main(int argc, const char* argv[]);
#include "include/core/federated/federate.h"
#include "include/core/federated/net_common.h"
#include "pythontarget.h"
// Code generated by the Lingua Franca compiler from:
// file://mnt/c/Users/jacky/Desktop/Memory_Leak/fed-gen/Main/src/client.lf
#define LOG_LEVEL 4
#define TARGET_FILES_DIRECTORY "/mnt/c/Users/jacky/Desktop/Memory_Leak/fed-gen/Main/src-gen/client"
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-k", "true", "-o", "10", "sec" };
void _lf_set_default_command_line_options() {
        default_argc = 6;
        default_argv = _lf_default_argv;
}
#include "clientreactor393266340.h"
#include "client341582687_main.h"
#include "include/_client_preamble.h"
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t** _lf_timer_triggers = NULL;
int _lf_timer_triggers_size = 0;
// Array of pointers to startup triggers.
reaction_t* _lf_startup_reactions[1];
int _lf_startup_reactions_size = 1;
// Array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
// Array of pointers to reset triggers.
reaction_t** _lf_reset_reactions = NULL;
int _lf_reset_reactions_size = 0;
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    // Create the array that will contain pointers to is_present fields to reset on each step.
    _lf_is_present_fields_size = 4;
    _lf_is_present_fields = (bool**)calloc(4, sizeof(bool*));
    if (_lf_is_present_fields == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated = (bool**)calloc(4, sizeof(bool*));
    if (_lf_is_present_fields_abbreviated == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated_size = 0;
    #ifdef FEDERATED_DECENTRALIZED
    // Create the array that will contain pointers to intended_tag fields to reset on each step.
    _lf_intended_tag_fields_size = 4;
    _lf_intended_tag_fields = (tag_t**)malloc(_lf_intended_tag_fields_size * sizeof(tag_t*));
    
    #endif // FEDERATED_DECENTRALIZED
    int _lf_startup_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_startup_reactions_count);
    int _lf_shutdown_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_shutdown_reactions_count);
    int _lf_reset_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_reset_reactions_count);
    int _lf_timer_triggers_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_timer_triggers_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    _client341582687_main_main_self_t* client_main_self[1];
    SUPPRESS_UNUSED_WARNING(client_main_self);
    _clientreactor393266340_self_t* client_client_self[1];
    SUPPRESS_UNUSED_WARNING(client_client_self);
    // ***** Start initializing client of class client
    client_main_self[0] = new_client341582687_main();
    client_main_self[0]->_lf_name = "client_main_lf";
    // Initializing action client.outputControlReactionTrigger
    client_main_self[0]->_lf__outputControlReactionTrigger.offset = 0;
    client_main_self[0]->_lf__outputControlReactionTrigger.period = -1;
    client_main_self[0]->_lf__outputControlReactionTrigger.mode = NULL;
    // Initializing action client.networkMessage_0
    client_main_self[0]->_lf__networkMessage_0.offset = 0;
    client_main_self[0]->_lf__networkMessage_0.period = -1;
    client_main_self[0]->_lf__networkMessage_0.mode = NULL;
    _lf_initialize_template((token_template_t*)
            &(client_main_self[0]->_lf__outputControlReactionTrigger),
    0);
    client_main_self[0]->_lf__outputControlReactionTrigger.status = absent;
    _lf_initialize_template((token_template_t*)
            &(client_main_self[0]->_lf__networkMessage_0),
    0);
    client_main_self[0]->_lf__networkMessage_0.status = absent;
    client_main_self[0]->_lf__reaction_0.deadline = NEVER;
    client_main_self[0]->_lf__reaction_1.deadline = NEVER;
    client_main_self[0]->_lf__reaction_2.deadline = NEVER;
    {
        // ***** Start initializing client.client of class ClientReactor
        client_client_self[0] = new_clientreactor393266340();
        client_client_self[0]->_lf_name = "client_client_lf";
        client_client_self[0]->_lf_py_reaction_function_0 = 
        get_python_function("__main__", 
            client_client_self[0]->_lf_name,
            0,
            "reaction_function_0");
        if(client_client_self[0]->_lf_py_reaction_function_0 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_0");
        }
        client_client_self[0]->_lf_py_reaction_function_1 = 
        get_python_function("__main__", 
            client_client_self[0]->_lf_name,
            0,
            "reaction_function_1");
        if(client_client_self[0]->_lf_py_reaction_function_1 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_1");
        }
        // width of -2 indicates that it is not a multiport.
        client_client_self[0]->_lf_out_parameter_width = -2;
        // width of -2 indicates that it is not a multiport.
        client_client_self[0]->_lf_in_parameter_width = -2;
        _lf_startup_reactions[_lf_startup_reactions_count++] = &client_client_self[0]->_lf__reaction_0;
        client_client_self[0]->_lf__reaction_0.deadline = NEVER;
        client_client_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing client.client
    }
    //***** End initializing client
    // **** Start deferred initialize for client
    {
        client_main_self[0]->_lf__reaction_0.name = "client reaction 0";
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of client.
        client_main_self[0]->_lf__reaction_0.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 0 of client
        client_main_self[0]->_lf__reaction_1.name = "client reaction 1";
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of client.
        client_main_self[0]->_lf__reaction_1.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 1 of client
        client_main_self[0]->_lf__reaction_2.name = "client reaction 2";
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_2 of client.
        client_main_self[0]->_lf__reaction_2.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        client_main_self[0]->_lf__reaction_2.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &client_main_self[0]->base.allocations);
        client_main_self[0]->_lf__reaction_2.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &client_main_self[0]->base.allocations);
        client_main_self[0]->_lf__reaction_2.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &client_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                client_main_self[0]->_lf__reaction_2.output_produced[count++] = &client_main_self[0]->_lf_client.in_parameter.is_present;
            }
        }
        
        // ** End initialization for reaction 2 of client
        // **** Start deferred initialize for client.client
        {
            client_client_self[0]->_lf__reaction_0.name = "client.client reaction 0";
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of client.client.
            client_client_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of client.client
            client_client_self[0]->_lf__reaction_1.name = "client.client reaction 1";
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of client.client.
            client_client_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            client_client_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &client_client_self[0]->base.allocations);
            client_client_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &client_client_self[0]->base.allocations);
            client_client_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &client_client_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    client_client_self[0]->_lf__reaction_1.output_produced[count++] = &client_client_self[0]->_lf_out_parameter.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of client.client
        }
        // **** End of deferred initialize for client.client
    }
    // **** End of deferred initialize for client
    // **** Start non-nested deferred initialize for client
    // Set number of destination reactors for port client.in_parameter.
    // Iterate over range client.client.in_parameter(0,1)->[client.client.in_parameter(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        client_main_self[src_runtime]->_lf_client.in_parameter.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range client.client.in_parameter(0,1)->[client.client.in_parameter(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 2 of client triggers 1 downstream reactions
            // through port client.client.in_parameter.
            client_main_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 2 of client, allocate an
            // array of trigger pointers for downstream reactions through port client.client.in_parameter
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &client_main_self[src_runtime]->base.allocations); 
            client_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges client.client.in_parameter(0,1)->[client.client.in_parameter(0,1)] and client.client.in_parameter(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range client.client.in_parameter(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port client.client.in_parameter's trigger struct.
                client_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &client_client_self[dst_runtime]->_lf__in_parameter;
            }
        }
    }
    // **** Start non-nested deferred initialize for client.client
    // For reference counting, set num_destinations for port client.client.out_parameter.
    // Iterate over range client.client.out_parameter(0,1)->[client.client.out_parameter(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        client_client_self[src_runtime]->_lf_out_parameter.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range client.client.out_parameter(0,1)->[client.client.out_parameter(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of client.client triggers 1 downstream reactions
            // through port client.client.out_parameter.
            client_client_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of client.client, allocate an
            // array of trigger pointers for downstream reactions through port client.client.out_parameter
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &client_client_self[src_runtime]->base.allocations); 
            client_client_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges client.client.out_parameter(0,1)->[client.client.out_parameter(0,1)] and client.client.out_parameter(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range client.client.out_parameter(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Port client.client.out_parameter has reactions in its parent's parent.
                // Point to the trigger struct for those reactions.
                client_client_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &client_main_self[dst_runtime]->_lf_client.out_parameter_trigger;
            }
        }
    }
    // **** End of non-nested deferred initialize for client.client
    // **** End of non-nested deferred initialize for client
    // Connect inputs and outputs for reactor client.
    // Connect inputs and outputs for reactor client.client.
    // Connect client.client.in_parameter(0,1)->[client.client.in_parameter(0,1)] to port client.client.in_parameter(0,1)
    // Iterate over ranges client.client.in_parameter(0,1)->[client.client.in_parameter(0,1)] and client.client.in_parameter(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range client.client.in_parameter(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            client_client_self[dst_runtime]->_lf_in_parameter = (clientreactor393266340_in_parameter_t*)&client_main_self[src_runtime]->_lf_client.in_parameter;
        }
    }
    // Connect client.client.out_parameter(0,1)->[client.client.out_parameter(0,1)] to port client.client.out_parameter(0,1)
    // Iterate over ranges client.client.out_parameter(0,1)->[client.client.out_parameter(0,1)] and client.client.out_parameter(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range client.client.out_parameter(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            client_main_self[dst_runtime]->_lf_client.out_parameter = (clientreactor393266340_out_parameter_t*)&client_client_self[src_runtime]->_lf_out_parameter;
        }
    }
    {
    }
    // Add port client.client.in_parameter to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                _lf_is_present_fields[0 + count] = &client_main_self[0]->_lf_client.in_parameter.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                _lf_intended_tag_fields[0 + count] = &client_main_self[0]->_lf_client.in_parameter.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        // Add action client.outputControlReactionTrigger to array of is_present fields.
        _lf_is_present_fields[1] 
                = &client_main_self[0]->_lf_outputControlReactionTrigger.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action client.outputControlReactionTrigger to array of intended_tag fields.
        _lf_intended_tag_fields[1] 
                = &client_main_self[0]->_lf_outputControlReactionTrigger.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action client.networkMessage_0 to array of is_present fields.
        _lf_is_present_fields[2] 
                = &client_main_self[0]->_lf_networkMessage_0.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action client.networkMessage_0 to array of intended_tag fields.
        _lf_intended_tag_fields[2] 
                = &client_main_self[0]->_lf_networkMessage_0.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port client.client.out_parameter to array of is_present fields.
            _lf_is_present_fields[3 + count] = &client_client_self[0]->_lf_out_parameter.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port client.client.out_parameter to array of intended_tag fields.
            _lf_intended_tag_fields[3 + count] = &client_client_self[0]->_lf_out_parameter.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    // Set reaction priorities for ReactorInstance client
    {
        client_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 2 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        client_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0002LL;
        client_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 2 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        client_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0002LL;
        client_main_self[0]->_lf__reaction_2.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        client_main_self[0]->_lf__reaction_2.index = 0xffffffffffff0000LL;
        // Set reaction priorities for ReactorInstance client.client
        {
            client_client_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            client_client_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            client_client_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            client_client_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        }
    }
    // Initialize the scheduler
    size_t num_reactions_per_level[3] = 
        {2, 1, 2};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 3};
    lf_sched_init(
        (size_t)_lf_number_of_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble();
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void _lf_trigger_startup_reactions() {
    for (int i = 0; i < _lf_startup_reactions_size; i++) {
        if (_lf_startup_reactions[i] != NULL) {
            _lf_trigger_reaction(_lf_startup_reactions[i], -1);
        }
    }
}
void _lf_initialize_timers() {
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED
}
bool _lf_trigger_shutdown_reactions() {
    return false;
}
#ifndef FEDERATED
void terminate_execution() {}
#endif
