#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
int lf_reactor_c_main(int argc, const char* argv[]);
#include "pythontarget.h"
// Code generated by the Lingua Franca compiler from:
// file://mnt/c/Users/jacky/Desktop/Memory_Leak/src/Main.lf
#define LOG_LEVEL 4
#define TARGET_FILES_DIRECTORY "/mnt/c/Users/jacky/Desktop/Memory_Leak/src-gen/Main"
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-o", "10", "sec" };
void _lf_set_default_command_line_options() {
        default_argc = 4;
        default_argv = _lf_default_argv;
}
#include "clientreactor1101451553.h"
#include "serverreactor1329897103.h"
#include "_lf_gendelay_0542839598.h"
#include "main1472012329_main.h"
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t** _lf_timer_triggers = NULL;
int _lf_timer_triggers_size = 0;
// Array of pointers to startup triggers.
reaction_t* _lf_startup_reactions[2];
int _lf_startup_reactions_size = 2;
// Array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
// Array of pointers to reset triggers.
reaction_t** _lf_reset_reactions = NULL;
int _lf_reset_reactions_size = 0;
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    // Create the array that will contain pointers to is_present fields to reset on each step.
    _lf_is_present_fields_size = 4;
    _lf_is_present_fields = (bool**)calloc(4, sizeof(bool*));
    if (_lf_is_present_fields == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated = (bool**)calloc(4, sizeof(bool*));
    if (_lf_is_present_fields_abbreviated == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated_size = 0;
    #ifdef FEDERATED_DECENTRALIZED
    // Create the array that will contain pointers to intended_tag fields to reset on each step.
    _lf_intended_tag_fields_size = 4;
    _lf_intended_tag_fields = (tag_t**)malloc(_lf_intended_tag_fields_size * sizeof(tag_t*));
    
    #endif // FEDERATED_DECENTRALIZED
    int _lf_startup_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_startup_reactions_count);
    int _lf_shutdown_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_shutdown_reactions_count);
    int _lf_reset_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_reset_reactions_count);
    int _lf_timer_triggers_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_timer_triggers_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    _main1472012329_main_main_self_t* main_main_self[1];
    SUPPRESS_UNUSED_WARNING(main_main_self);
    _clientreactor1101451553_self_t* main_client_self[1];
    SUPPRESS_UNUSED_WARNING(main_client_self);
    _serverreactor1329897103_self_t* main_server_self[1];
    SUPPRESS_UNUSED_WARNING(main_server_self);
    __lf_gendelay_0542839598_self_t* main_delay_self[1];
    SUPPRESS_UNUSED_WARNING(main_delay_self);
    // ***** Start initializing Main of class Main
    main_main_self[0] = new_main1472012329_main();
    main_main_self[0]->_lf_name = "main_main_lf";
    {
        // ***** Start initializing Main.client of class ClientReactor
        main_client_self[0] = new_clientreactor1101451553();
        main_client_self[0]->_lf_name = "main_client_lf";
        main_client_self[0]->_lf_py_reaction_function_0 = 
        get_python_function("__main__", 
            main_client_self[0]->_lf_name,
            0,
            "reaction_function_0");
        if(main_client_self[0]->_lf_py_reaction_function_0 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_0");
        }
        main_client_self[0]->_lf_py_reaction_function_1 = 
        get_python_function("__main__", 
            main_client_self[0]->_lf_name,
            0,
            "reaction_function_1");
        if(main_client_self[0]->_lf_py_reaction_function_1 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_1");
        }
        // width of -2 indicates that it is not a multiport.
        main_client_self[0]->_lf_out_parameter_width = -2;
        // width of -2 indicates that it is not a multiport.
        main_client_self[0]->_lf_in_parameter_width = -2;
        _lf_startup_reactions[_lf_startup_reactions_count++] = &main_client_self[0]->_lf__reaction_0;
        main_client_self[0]->_lf__reaction_0.deadline = NEVER;
        main_client_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing Main.client
    }
    {
        // ***** Start initializing Main.server of class ServerReactor
        main_server_self[0] = new_serverreactor1329897103();
        main_server_self[0]->_lf_name = "main_server_lf";
        main_server_self[0]->_lf_py_reaction_function_0 = 
        get_python_function("__main__", 
            main_server_self[0]->_lf_name,
            0,
            "reaction_function_0");
        if(main_server_self[0]->_lf_py_reaction_function_0 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_0");
        }
        main_server_self[0]->_lf_py_reaction_function_1 = 
        get_python_function("__main__", 
            main_server_self[0]->_lf_name,
            0,
            "reaction_function_1");
        if(main_server_self[0]->_lf_py_reaction_function_1 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_1");
        }
        // width of -2 indicates that it is not a multiport.
        main_server_self[0]->_lf_out_parameter_width = -2;
        // width of -2 indicates that it is not a multiport.
        main_server_self[0]->_lf_in_parameter_width = -2;
        _lf_startup_reactions[_lf_startup_reactions_count++] = &main_server_self[0]->_lf__reaction_0;
        main_server_self[0]->_lf__reaction_0.deadline = NEVER;
        main_server_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing Main.server
    }
    {
        // ***** Start initializing Main.delay of class _lf_GenDelay_0
        main_delay_self[0] = new__lf_gendelay_0542839598();
        main_delay_self[0]->_lf_name = "main_delay_lf";
        // width of -2 indicates that it is not a multiport.
        main_delay_self[0]->_lf_out_width = -2;
        // width of -2 indicates that it is not a multiport.
        main_delay_self[0]->_lf_inp_width = -2;
        // Initializing action Main.delay.act
        main_delay_self[0]->_lf__act.offset = 0;
        main_delay_self[0]->_lf__act.period = -1;
        main_delay_self[0]->_lf__act.mode = NULL;
        _lf_initialize_template((token_template_t*)
                &(main_delay_self[0]->_lf__act),
        0);
        main_delay_self[0]->_lf__act.status = absent;
        main_delay_self[0]->_lf__reaction_0.deadline = NEVER;
        main_delay_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing Main.delay
    }
    //***** End initializing Main
    // **** Start deferred initialize for Main
    {
        // **** Start deferred initialize for Main.client
        {
            main_client_self[0]->_lf__reaction_0.name = "Main.client reaction 0";
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of Main.client.
            main_client_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of Main.client
            main_client_self[0]->_lf__reaction_1.name = "Main.client reaction 1";
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of Main.client.
            main_client_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            main_client_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &main_client_self[0]->base.allocations);
            main_client_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &main_client_self[0]->base.allocations);
            main_client_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &main_client_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    main_client_self[0]->_lf__reaction_1.output_produced[count++] = &main_client_self[0]->_lf_out_parameter.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of Main.client
        }
        // **** End of deferred initialize for Main.client
        // **** Start deferred initialize for Main.server
        {
            main_server_self[0]->_lf__reaction_0.name = "Main.server reaction 0";
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of Main.server.
            main_server_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            main_server_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &main_server_self[0]->base.allocations);
            main_server_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &main_server_self[0]->base.allocations);
            main_server_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &main_server_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    main_server_self[0]->_lf__reaction_0.output_produced[count++] = &main_server_self[0]->_lf_out_parameter.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of Main.server
            main_server_self[0]->_lf__reaction_1.name = "Main.server reaction 1";
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of Main.server.
            main_server_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            main_server_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &main_server_self[0]->base.allocations);
            main_server_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &main_server_self[0]->base.allocations);
            main_server_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &main_server_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    main_server_self[0]->_lf__reaction_1.output_produced[count++] = &main_server_self[0]->_lf_out_parameter.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of Main.server
        }
        // **** End of deferred initialize for Main.server
        // **** Start deferred initialize for Main.delay
        {
            main_delay_self[0]->_lf__reaction_0.name = "Main.delay reaction 0";
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of Main.delay.
            main_delay_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            main_delay_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &main_delay_self[0]->base.allocations);
            main_delay_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &main_delay_self[0]->base.allocations);
            main_delay_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &main_delay_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    main_delay_self[0]->_lf__reaction_0.output_produced[count++] = &main_delay_self[0]->_lf_out.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of Main.delay
            main_delay_self[0]->_lf__reaction_1.name = "Main.delay reaction 1";
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of Main.delay.
            main_delay_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of Main.delay
        }
        // **** End of deferred initialize for Main.delay
    }
    // **** End of deferred initialize for Main
    // **** Start non-nested deferred initialize for Main
    // **** Start non-nested deferred initialize for Main.client
    // For reference counting, set num_destinations for port Main.client.out_parameter.
    // Iterate over range Main.client.out_parameter(0,1)->[Main.server.in_parameter(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        main_client_self[src_runtime]->_lf_out_parameter.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range Main.client.out_parameter(0,1)->[Main.server.in_parameter(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of Main.client triggers 1 downstream reactions
            // through port Main.client.out_parameter.
            main_client_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of Main.client, allocate an
            // array of trigger pointers for downstream reactions through port Main.client.out_parameter
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &main_client_self[src_runtime]->base.allocations); 
            main_client_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges Main.client.out_parameter(0,1)->[Main.server.in_parameter(0,1)] and Main.server.in_parameter(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range Main.server.in_parameter(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port Main.server.in_parameter's trigger struct.
                main_client_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &main_server_self[dst_runtime]->_lf__in_parameter;
            }
        }
    }
    // **** End of non-nested deferred initialize for Main.client
    // **** Start non-nested deferred initialize for Main.server
    // For reference counting, set num_destinations for port Main.server.out_parameter.
    // Iterate over range Main.server.out_parameter(0,1)->[Main.delay.inp(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        main_server_self[src_runtime]->_lf_out_parameter.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range Main.server.out_parameter(0,1)->[Main.delay.inp(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of Main.server triggers 1 downstream reactions
            // through port Main.server.out_parameter.
            main_server_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of Main.server, allocate an
            // array of trigger pointers for downstream reactions through port Main.server.out_parameter
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &main_server_self[src_runtime]->base.allocations); 
            main_server_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges Main.server.out_parameter(0,1)->[Main.delay.inp(0,1)] and Main.delay.inp(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range Main.delay.inp(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port Main.delay.inp's trigger struct.
                main_server_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &main_delay_self[dst_runtime]->_lf__inp;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range Main.server.out_parameter(0,1)->[Main.delay.inp(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of Main.server triggers 1 downstream reactions
            // through port Main.server.out_parameter.
            main_server_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of Main.server, allocate an
            // array of trigger pointers for downstream reactions through port Main.server.out_parameter
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &main_server_self[src_runtime]->base.allocations); 
            main_server_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges Main.server.out_parameter(0,1)->[Main.delay.inp(0,1)] and Main.delay.inp(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range Main.delay.inp(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port Main.delay.inp's trigger struct.
                main_server_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &main_delay_self[dst_runtime]->_lf__inp;
            }
        }
    }
    // **** End of non-nested deferred initialize for Main.server
    // **** Start non-nested deferred initialize for Main.delay
    // For reference counting, set num_destinations for port Main.delay.out.
    // Iterate over range Main.delay.out(0,1)->[Main.client.in_parameter(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        main_delay_self[src_runtime]->_lf_out.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range Main.delay.out(0,1)->[Main.client.in_parameter(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of Main.delay triggers 1 downstream reactions
            // through port Main.delay.out.
            main_delay_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of Main.delay, allocate an
            // array of trigger pointers for downstream reactions through port Main.delay.out
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &main_delay_self[src_runtime]->base.allocations); 
            main_delay_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges Main.delay.out(0,1)->[Main.client.in_parameter(0,1)] and Main.client.in_parameter(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range Main.client.in_parameter(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port Main.client.in_parameter's trigger struct.
                main_delay_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &main_client_self[dst_runtime]->_lf__in_parameter;
            }
        }
    }
    // **** End of non-nested deferred initialize for Main.delay
    // **** End of non-nested deferred initialize for Main
    // Connect inputs and outputs for reactor Main.
    // Connect inputs and outputs for reactor Main.client.
    // Connect Main.client.out_parameter(0,1)->[Main.server.in_parameter(0,1)] to port Main.server.in_parameter(0,1)
    // Iterate over ranges Main.client.out_parameter(0,1)->[Main.server.in_parameter(0,1)] and Main.server.in_parameter(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range Main.server.in_parameter(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            main_server_self[dst_runtime]->_lf_in_parameter = (serverreactor1329897103_in_parameter_t*)&main_client_self[src_runtime]->_lf_out_parameter;
        }
    }
    // Connect inputs and outputs for reactor Main.server.
    // Connect Main.server.out_parameter(0,1)->[Main.delay.inp(0,1)] to port Main.delay.inp(0,1)
    // Iterate over ranges Main.server.out_parameter(0,1)->[Main.delay.inp(0,1)] and Main.delay.inp(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range Main.delay.inp(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            main_delay_self[dst_runtime]->_lf_inp = (_lf_gendelay_0542839598_inp_t*)&main_server_self[src_runtime]->_lf_out_parameter;
        }
    }
    // Connect inputs and outputs for reactor Main.delay.
    // Connect Main.delay.out(0,1)->[Main.client.in_parameter(0,1)] to port Main.client.in_parameter(0,1)
    // Iterate over ranges Main.delay.out(0,1)->[Main.client.in_parameter(0,1)] and Main.client.in_parameter(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range Main.client.in_parameter(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            main_client_self[dst_runtime]->_lf_in_parameter = (clientreactor1101451553_in_parameter_t*)&main_delay_self[src_runtime]->_lf_out;
        }
    }
    {
    }
    {
    }
    {
        {
            // Add action Main.delay.act to array of is_present fields.
            _lf_is_present_fields[0] 
                    = &main_delay_self[0]->_lf_act.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add action Main.delay.act to array of intended_tag fields.
            _lf_intended_tag_fields[0] 
                    = &main_delay_self[0]->_lf_act.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port Main.client.out_parameter to array of is_present fields.
            _lf_is_present_fields[1 + count] = &main_client_self[0]->_lf_out_parameter.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port Main.client.out_parameter to array of intended_tag fields.
            _lf_intended_tag_fields[1 + count] = &main_client_self[0]->_lf_out_parameter.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port Main.server.out_parameter to array of is_present fields.
            _lf_is_present_fields[2 + count] = &main_server_self[0]->_lf_out_parameter.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port Main.server.out_parameter to array of intended_tag fields.
            _lf_intended_tag_fields[2 + count] = &main_server_self[0]->_lf_out_parameter.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port Main.delay.out to array of is_present fields.
            _lf_is_present_fields[3 + count] = &main_delay_self[0]->_lf_out.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port Main.delay.out to array of intended_tag fields.
            _lf_intended_tag_fields[3 + count] = &main_delay_self[0]->_lf_out.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    // Set reaction priorities for ReactorInstance Main
    {
        // Set reaction priorities for ReactorInstance Main.client
        {
            main_client_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            main_client_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            main_client_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            main_client_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        }
        // Set reaction priorities for ReactorInstance Main.server
        {
            main_server_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            main_server_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            main_server_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            main_server_self[0]->_lf__reaction_1.index = 0xffffffffffff0002LL;
        }
        // Set reaction priorities for ReactorInstance Main.delay
        {
            main_delay_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            main_delay_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            main_delay_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 3 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            main_delay_self[0]->_lf__reaction_1.index = 0xffffffffffff0003LL;
        }
    }
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble();
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void _lf_trigger_startup_reactions() {
    for (int i = 0; i < _lf_startup_reactions_size; i++) {
        if (_lf_startup_reactions[i] != NULL) {
            _lf_trigger_reaction(_lf_startup_reactions[i], -1);
        }
    }
}
void _lf_initialize_timers() {
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED
}
bool _lf_trigger_shutdown_reactions() {
    return false;
}
#ifndef FEDERATED
void terminate_execution() {}
#endif
